/*
 * AMBAR compile-time build profiles and feature identity.
 *
 * NORMAL is deliberately the default. CONTINUOUS_HIL is the forced-stroke
 * endurance image. VARIABLE_HIL is the causal fractional-controller image.
 * Each must be selected explicitly and is reported over protocol-v2 so host
 * preflight can refuse the wrong image.
 */

#ifndef AMBAR_FEATURES_H
#define AMBAR_FEATURES_H

#include <stdint.h>

#define AMBAR_BUILD_PROFILE_NORMAL         0
#define AMBAR_BUILD_PROFILE_CONTINUOUS_HIL 1
#define AMBAR_BUILD_PROFILE_VARIABLE_HIL   2

#ifndef AMBAR_BUILD_PROFILE
#define AMBAR_BUILD_PROFILE AMBAR_BUILD_PROFILE_NORMAL
#endif

#if ((AMBAR_BUILD_PROFILE != AMBAR_BUILD_PROFILE_NORMAL) && \
     (AMBAR_BUILD_PROFILE != AMBAR_BUILD_PROFILE_CONTINUOUS_HIL) && \
     (AMBAR_BUILD_PROFILE != AMBAR_BUILD_PROFILE_VARIABLE_HIL))
#error "AMBAR_BUILD_PROFILE must be NORMAL (0), CONTINUOUS_HIL (1), or VARIABLE_HIL (2)"
#endif

#define AMBAR_BUILD_IS_NORMAL \
    (AMBAR_BUILD_PROFILE == AMBAR_BUILD_PROFILE_NORMAL)
#define AMBAR_BUILD_IS_CONTINUOUS_HIL \
    (AMBAR_BUILD_PROFILE == AMBAR_BUILD_PROFILE_CONTINUOUS_HIL)
#define AMBAR_BUILD_IS_VARIABLE_HIL \
    (AMBAR_BUILD_PROFILE == AMBAR_BUILD_PROFILE_VARIABLE_HIL)
#define AMBAR_BUILD_IS_HIL \
    (AMBAR_BUILD_IS_CONTINUOUS_HIL || AMBAR_BUILD_IS_VARIABLE_HIL)

/* ===================== PROFILE DEFAULTS ===================== */

#ifndef AMBAR_FEATURE_RADIO
#define AMBAR_FEATURE_RADIO AMBAR_BUILD_IS_NORMAL
#endif
#ifndef AMBAR_FEATURE_TELEMETRY
#define AMBAR_FEATURE_TELEMETRY AMBAR_BUILD_IS_NORMAL
#endif
#ifndef AMBAR_FEATURE_RADIO_HEARTBEAT
#define AMBAR_FEATURE_RADIO_HEARTBEAT AMBAR_BUILD_IS_NORMAL
#endif
#ifndef AMBAR_FEATURE_USB_PROTOCOL
#define AMBAR_FEATURE_USB_PROTOCOL 1
#endif
#ifndef AMBAR_FEATURE_SIMULATION_INPUT
#define AMBAR_FEATURE_SIMULATION_INPUT AMBAR_BUILD_IS_HIL
#endif
#ifndef AMBAR_FEATURE_HIL_OVERRIDE
#define AMBAR_FEATURE_HIL_OVERRIDE AMBAR_BUILD_IS_CONTINUOUS_HIL
#endif
#ifndef AMBAR_FEATURE_USB_REQUIRE_VBUS_SENSE
#define AMBAR_FEATURE_USB_REQUIRE_VBUS_SENSE 1
#endif
#ifndef AMBAR_FEATURE_USB_FLASH_MAINTENANCE
#define AMBAR_FEATURE_USB_FLASH_MAINTENANCE 0
#endif
#ifndef AMBAR_FEATURE_FLASH_LOGGING
#define AMBAR_FEATURE_FLASH_LOGGING AMBAR_BUILD_IS_NORMAL
#endif
#ifndef AMBAR_FEATURE_ACTUATOR
#define AMBAR_FEATURE_ACTUATOR 1
#endif
#ifndef AMBAR_FEATURE_BENCH_ACTUATOR_COMMANDS
#define AMBAR_FEATURE_BENCH_ACTUATOR_COMMANDS AMBAR_BUILD_IS_CONTINUOUS_HIL
#endif
#ifndef AMBAR_FEATURE_AUTOMATIC_ACTUATION
#define AMBAR_FEATURE_AUTOMATIC_ACTUATION \
    (AMBAR_BUILD_IS_NORMAL || AMBAR_BUILD_IS_VARIABLE_HIL)
#endif
#ifndef AMBAR_FEATURE_WATCHDOG
#define AMBAR_FEATURE_WATCHDOG AMBAR_BUILD_IS_NORMAL
#endif
#ifndef AMBAR_FEATURE_MAGNETOMETER_TELEMETRY
#define AMBAR_FEATURE_MAGNETOMETER_TELEMETRY 1
#endif
#ifndef AMBAR_FEATURE_VERBOSE_STATUS_TEXT
#define AMBAR_FEATURE_VERBOSE_STATUS_TEXT AMBAR_BUILD_IS_NORMAL
#endif
#ifndef AMBAR_FEATURE_AUTO_FLIGHT_PHASES
#define AMBAR_FEATURE_AUTO_FLIGHT_PHASES 1
#endif

/*
 * Hardware geometry/current profile is independent of NORMAL versus HIL.  Both
 * images run on the same PCB and therefore use the same three-rotation travel.
 */
#ifndef AMBAR_ACTUATOR_USE_PROTOTYPE_PROFILE
#define AMBAR_ACTUATOR_USE_PROTOTYPE_PROFILE 1
#endif
#ifndef AMBAR_ACTUATOR_DIRECTION_INVERTED
#define AMBAR_ACTUATOR_DIRECTION_INVERTED 0
#endif

/* Compatibility aliases for older project-owned source references. */
#define AMBAR_FEATURE_PRESENTATION_MOTION AMBAR_FEATURE_HIL_OVERRIDE
#define AMBAR_PRESENTATION_ACTUATOR_DIRECTION_INVERTED \
    AMBAR_ACTUATOR_DIRECTION_INVERTED

/* ===================== COMPILE-TIME VALIDATION ===================== */

#define AMBAR_VALIDATE_BOOLEAN_(name) \
    typedef char ambar_validate_##name[((name) == 0 || (name) == 1) ? 1 : -1]

AMBAR_VALIDATE_BOOLEAN_(AMBAR_FEATURE_RADIO);
AMBAR_VALIDATE_BOOLEAN_(AMBAR_FEATURE_TELEMETRY);
AMBAR_VALIDATE_BOOLEAN_(AMBAR_FEATURE_RADIO_HEARTBEAT);
AMBAR_VALIDATE_BOOLEAN_(AMBAR_FEATURE_USB_PROTOCOL);
AMBAR_VALIDATE_BOOLEAN_(AMBAR_FEATURE_SIMULATION_INPUT);
AMBAR_VALIDATE_BOOLEAN_(AMBAR_FEATURE_HIL_OVERRIDE);
AMBAR_VALIDATE_BOOLEAN_(AMBAR_FEATURE_USB_REQUIRE_VBUS_SENSE);
AMBAR_VALIDATE_BOOLEAN_(AMBAR_FEATURE_USB_FLASH_MAINTENANCE);
AMBAR_VALIDATE_BOOLEAN_(AMBAR_FEATURE_FLASH_LOGGING);
AMBAR_VALIDATE_BOOLEAN_(AMBAR_FEATURE_ACTUATOR);
AMBAR_VALIDATE_BOOLEAN_(AMBAR_FEATURE_BENCH_ACTUATOR_COMMANDS);
AMBAR_VALIDATE_BOOLEAN_(AMBAR_FEATURE_AUTOMATIC_ACTUATION);
AMBAR_VALIDATE_BOOLEAN_(AMBAR_FEATURE_WATCHDOG);
AMBAR_VALIDATE_BOOLEAN_(AMBAR_FEATURE_MAGNETOMETER_TELEMETRY);
AMBAR_VALIDATE_BOOLEAN_(AMBAR_FEATURE_VERBOSE_STATUS_TEXT);
AMBAR_VALIDATE_BOOLEAN_(AMBAR_FEATURE_AUTO_FLIGHT_PHASES);
AMBAR_VALIDATE_BOOLEAN_(AMBAR_ACTUATOR_USE_PROTOTYPE_PROFILE);
AMBAR_VALIDATE_BOOLEAN_(AMBAR_ACTUATOR_DIRECTION_INVERTED);

#undef AMBAR_VALIDATE_BOOLEAN_

#if AMBAR_BUILD_IS_NORMAL && AMBAR_FEATURE_SIMULATION_INPUT
#error "NORMAL must not accept simulation input"
#endif
#if AMBAR_BUILD_IS_NORMAL && AMBAR_FEATURE_HIL_OVERRIDE
#error "NORMAL must not accept HIL override"
#endif
#if AMBAR_BUILD_IS_NORMAL && AMBAR_FEATURE_BENCH_ACTUATOR_COMMANDS
#error "NORMAL must not expose arbitrary bench motion"
#endif
#if AMBAR_BUILD_IS_VARIABLE_HIL && AMBAR_FEATURE_HIL_OVERRIDE
#error "VARIABLE_HIL must not accept forced FULL/HOME override"
#endif
#if AMBAR_BUILD_IS_VARIABLE_HIL && AMBAR_FEATURE_BENCH_ACTUATOR_COMMANDS
#error "VARIABLE_HIL must not expose arbitrary bench motion"
#endif
#if AMBAR_BUILD_IS_VARIABLE_HIL && (!AMBAR_FEATURE_USB_PROTOCOL || \
                                    !AMBAR_FEATURE_SIMULATION_INPUT || \
                                    !AMBAR_FEATURE_ACTUATOR || \
                                    !AMBAR_FEATURE_AUTOMATIC_ACTUATION)
#error "VARIABLE_HIL requires USB simulation and automatic fractional actuation"
#endif
#if AMBAR_BUILD_IS_CONTINUOUS_HIL && AMBAR_FEATURE_AUTOMATIC_ACTUATION
#error "CONTINUOUS_HIL must keep controller output physically disconnected"
#endif

/* ===================== EFFECTIVE FEATURES ===================== */

#define AMBAR_FEATURE_EFFECTIVE_TELEMETRY \
    (AMBAR_FEATURE_RADIO && AMBAR_FEATURE_TELEMETRY)
#define AMBAR_FEATURE_EFFECTIVE_HEARTBEAT \
    (AMBAR_FEATURE_RADIO && AMBAR_FEATURE_RADIO_HEARTBEAT)
#define AMBAR_FEATURE_EFFECTIVE_BENCH_COMMANDS \
    (AMBAR_FEATURE_ACTUATOR && AMBAR_FEATURE_BENCH_ACTUATOR_COMMANDS)
#define AMBAR_FEATURE_EFFECTIVE_SIMULATION \
    (AMBAR_FEATURE_USB_PROTOCOL && AMBAR_FEATURE_SIMULATION_INPUT)
#define AMBAR_FEATURE_EFFECTIVE_HIL_OVERRIDE \
    (AMBAR_FEATURE_ACTUATOR && AMBAR_FEATURE_EFFECTIVE_SIMULATION && \
     AMBAR_FEATURE_HIL_OVERRIDE)
#define AMBAR_FEATURE_EFFECTIVE_USB_FLASH_MAINTENANCE \
    (AMBAR_FEATURE_USB_PROTOCOL && AMBAR_FEATURE_USB_FLASH_MAINTENANCE)

/* ===================== REPORTED BUILD IDENTITY ===================== */

/*
 * Heartbeat/config feature word:
 *   0 radio                 8 automatic flight phases
 *   1 radio telemetry       9 radio heartbeat
 *   2 onboard flight log   10 direct USB
 *   3 actuator             11 simulation input
 *   4 arbitrary bench cmd  12 VBUS sense required
 *   5 watchdog             13 USB flash maintenance
 *   6 magnetometer         14 CONTINUOUS_HIL profile
 *   7 verbose text         15 actuator direction inverted
 *                          16 VARIABLE_HIL profile
 */
#define AMBAR_FEATURE_ENABLED_BITS ( \
    ((uint32_t)AMBAR_FEATURE_RADIO << 0U) | \
    ((uint32_t)AMBAR_FEATURE_EFFECTIVE_TELEMETRY << 1U) | \
    ((uint32_t)AMBAR_FEATURE_FLASH_LOGGING << 2U) | \
    ((uint32_t)AMBAR_FEATURE_ACTUATOR << 3U) | \
    ((uint32_t)AMBAR_FEATURE_EFFECTIVE_BENCH_COMMANDS << 4U) | \
    ((uint32_t)AMBAR_FEATURE_WATCHDOG << 5U) | \
    ((uint32_t)AMBAR_FEATURE_MAGNETOMETER_TELEMETRY << 6U) | \
    ((uint32_t)AMBAR_FEATURE_VERBOSE_STATUS_TEXT << 7U) | \
    ((uint32_t)AMBAR_FEATURE_AUTO_FLIGHT_PHASES << 8U) | \
    ((uint32_t)AMBAR_FEATURE_EFFECTIVE_HEARTBEAT << 9U) | \
    ((uint32_t)AMBAR_FEATURE_USB_PROTOCOL << 10U) | \
    ((uint32_t)AMBAR_FEATURE_EFFECTIVE_SIMULATION << 11U) | \
    ((uint32_t)AMBAR_FEATURE_USB_REQUIRE_VBUS_SENSE << 12U) | \
    ((uint32_t)AMBAR_FEATURE_EFFECTIVE_USB_FLASH_MAINTENANCE << 13U) | \
    ((uint32_t)AMBAR_BUILD_IS_CONTINUOUS_HIL << 14U) | \
    ((uint32_t)AMBAR_ACTUATOR_DIRECTION_INVERTED << 15U) | \
    ((uint32_t)AMBAR_BUILD_IS_VARIABLE_HIL << 16U))

/* Legacy radio config flags have room for only the lower 16 feature bits. */
#define AMBAR_FEATURE_CONFIG_STATUS_FLAGS \
    ((AMBAR_FEATURE_ENABLED_BITS & 0xFFFFUL) << 16U)

#endif /* AMBAR_FEATURES_H */
