/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file           : main.h
  * @brief          : Header for main.c file.
  *                   This file contains the common defines of the application.
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2026 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */
/* USER CODE END Header */

/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef __MAIN_H
#define __MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

/* Includes ------------------------------------------------------------------*/
#include "stm32h5xx_hal.h"

/* Private includes ----------------------------------------------------------*/
/* USER CODE BEGIN Includes */

/* USER CODE END Includes */

/* Exported types ------------------------------------------------------------*/
/* USER CODE BEGIN ET */

/* USER CODE END ET */

/* Exported constants --------------------------------------------------------*/
/* USER CODE BEGIN EC */

/* USER CODE END EC */

/* Exported macro ------------------------------------------------------------*/
/* USER CODE BEGIN EM */

/* USER CODE END EM */

/* Exported functions prototypes ---------------------------------------------*/
void Error_Handler(void);

/* USER CODE BEGIN EFP */

/* USER CODE END EFP */

/* Private defines -----------------------------------------------------------*/
#define LED_4_Pin GPIO_PIN_0
#define LED_4_GPIO_Port GPIOC
#define LED_3_Pin GPIO_PIN_3
#define LED_3_GPIO_Port GPIOC
#define LED_2_Pin GPIO_PIN_0
#define LED_2_GPIO_Port GPIOA
#define LED_1_Pin GPIO_PIN_1
#define LED_1_GPIO_Port GPIOA
#define LORA_NRESET_Pin GPIO_PIN_2
#define LORA_NRESET_GPIO_Port GPIOA
#define LORA_CS_Pin GPIO_PIN_3
#define LORA_CS_GPIO_Port GPIOA
#define LORA_DIO1_Pin GPIO_PIN_4
#define LORA_DIO1_GPIO_Port GPIOC
#define LORA_BUSY_Pin GPIO_PIN_5
#define LORA_BUSY_GPIO_Port GPIOC
#define MOTOR_CS_Pin GPIO_PIN_0
#define MOTOR_CS_GPIO_Port GPIOB
#define MOTOR_DRV_ENN_Pin GPIO_PIN_1
#define MOTOR_DRV_ENN_GPIO_Port GPIOB
#define MOTOR_SLEEPN_Pin GPIO_PIN_2
#define MOTOR_SLEEPN_GPIO_Port GPIOB
#define BARO_INT_Pin GPIO_PIN_14
#define BARO_INT_GPIO_Port GPIOB
#define MOTOR_DIAG1_Pin GPIO_PIN_15
#define MOTOR_DIAG1_GPIO_Port GPIOB
#define MOTOR_DIAG0_Pin GPIO_PIN_7
#define MOTOR_DIAG0_GPIO_Port GPIOC
#define I2C3_INT_Pin GPIO_PIN_8
#define I2C3_INT_GPIO_Port GPIOC
#define USB_SENSE_Pin GPIO_PIN_9
#define USB_SENSE_GPIO_Port GPIOA
#define FLASH_CS_Pin GPIO_PIN_2
#define FLASH_CS_GPIO_Port GPIOD
#define LED_6_Pin GPIO_PIN_4
#define LED_6_GPIO_Port GPIOB
#define LED_5_Pin GPIO_PIN_5
#define LED_5_GPIO_Port GPIOB
#define I2C1_INT_Pin GPIO_PIN_6
#define I2C1_INT_GPIO_Port GPIOB

/* USER CODE BEGIN Private defines */
/*
 * Keep application-level constants in module headers instead of main.h when
 * possible.  This file is regenerated by CubeMX, so handwritten values are safer
 * inside USER CODE blocks or driver-specific headers.
 */

/* USER CODE END Private defines */

#ifdef __cplusplus
}
#endif

#endif /* __MAIN_H */
